[package]
authors.workspace = true
edition.workspace = true
name = "lustrefs-loadtest"
version.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive", "env", "wrap_help"] }
rand.workspace = true
reqwest = { workspace = true, features = ["rustls-tls"] }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "time",
    "sync",
] }

[lints]
workspace = true
